### ISSUE TITLE
Not able to Get it Working

### ISSUE THREAD

**Issue by anujdutt9** [ihassin/fruitymesh-ubuntu-vm#16]
Hello Sir. I have tried all the steps 3-4 time on windows, Linux/Ubuntu but I was not able to get it working. Can you please help me to get this working specially the part where you say that it can be controlled from raspberry pi terminal.

Thanks : )

**Comment by ihassin** [comment]
Thanks for writing about this.
I do not recall setting up a makefile or anything for programming FruityMesh via a Pi. The way I worked was cross-compiling for NRF51 using my Mac or a Linux box.

**Comment by anujdutt9** [comment]
Sir, I am talking about this part "Raspberry Pi cross-compiler toolchain" .
Here you say that "You should see the program compile and then run (on the Pi). " So, does that mean that instead of a Putty terminal I can control the "nRF51 dongle flashed with fruity mesh" from the "RPi terminal" or is it just to compile the code and generate the ".HEX" file ?
Thanks : )

**Comment by ihassin** [comment]
Oh I see the misunderstanding - "The Ansible script includes a role named 'pi' that sets up a cross compiler for the Raspberry Pi on the virtual machine". This installs a cross compiler to produce executables running on Pi from the VM. It's does not install a cross-compiler on the Pi to produce executables for the NRF51. I added it as a goodie for people to be able to program both NRF51 and Pi from the same VM. I did this because people experiment with BlueTooth on Pi's too...
